//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeunEvote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contestant
    {
        public int Id { get; set; }
        public string Nickname { get; set; }
        public string Party { get; set; }
        public int ElectionId { get; set; }
        public string ProfilePicturePath { get; set; }
        public int PartyPartyId { get; set; }
        public int Count { get; set; }
    
        public virtual Election Election { get; set; }
        public virtual Party Party1 { get; set; }
    }
}
