//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeunEvote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionDetail
    {
        public int Id { get; set; }
        public System.DateTime ElectionStartTime { get; set; }
        public System.DateTime ElectionStopTime { get; set; }
    }
}
