//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeunEvote.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IVotingModelEntities : DbContext
    {
        public IVotingModelEntities()
            : base("name=IVotingModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminee> Adminees { get; set; }
        public virtual DbSet<Contestant> Contestants { get; set; }
        public virtual DbSet<ElectionDetail> ElectionDetails { get; set; }
        public virtual DbSet<Election> Elections { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Voted> Voteds { get; set; }
        public virtual DbSet<VotersDet> VotersDets { get; set; }
    }
}
