//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeunEvote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotersDet
    {
        public int VoterId { get; set; }
        public string Surname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public int Age { get; set; }
        public string StateOfOrigin { get; set; }
        public string LocalGovt { get; set; }
        public string PhoneNumber { get; set; }
        public string NOKName { get; set; }
        public string NOKPhoneNo { get; set; }
        public string Passport { get; set; }
        public string CertificateOfOrigin { get; set; }
        public string BVN { get; set; }
    }
}
